### ISSUE TITLE
android 8.0 启动失败

### ISSUE THREAD

**Issue by gubojun** [G-Joker/WeaponApp#3]
## Runtime
```
Device : Android Emulator
SDK : Android 8.0
ABI : Intel x86
```
## Error Log
```
09-27 02:20:00.257 13868-13868/com.weapon.joker E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.weapon.joker, PID: 13868
                                                                  java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.weapon.joker/com.weapon.joker.app.main.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.weapon.joker.app.main.MainActivity" on path: DexPathList[[zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/base.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_dependencies_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_0_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_1_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_2_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_3_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_4_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_5_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_6_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_7_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_8_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/base.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /system/vendor/lib]]
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2718)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                      at android.os.Looper.loop(Looper.java:164)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
09-27 02:20:00.257 13868-13868/com.weapon.joker E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.weapon.joker.app.main.MainActivity" on path: DexPathList[[zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/base.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_dependencies_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_0_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_1_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_2_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_3_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_4_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_5_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_6_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_7_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_8_apk.apk", zip file "/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/base.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.weapon.joker-dnYmFL5OiDQq_adeQKfdVw==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /system/vendor/lib]]
                                                                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                      at android.app.Instrumentation.newActivity(Instrumentation.java:1173)
                                                                      at cn.jiguang.a.a.d.a.a.d.newActivity(Unknown Source:6)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708)
                                                                      	... 9 more
```

**Comment by WeaponZhi** [comment]
虚拟机跑的话，需要输入以下指令：
gradlew cleanLib
gradlew buildLib -q -Dbundle.arch=x86
gradlew cleanBundle
gradlew buildBundle -q -Dbundle.arch=x86

如果是真机，则最后的 x86 改成 armeabi 即可
编译相关的文档将更新到 README

**Comment by WeaponZhi** [comment]
Small 和 8.0 适配有问题
[https://github.com/wequick/Small/issues/518](https://github.com/wequick/Small/issues/518)
